<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Capítulo 3 | Análisis Series de Tiempo de un conjunto de datos de tráfico</title>
  <meta name="description" content="Durante el curso de Análisis de Series de Tiempo se trabajará con una base de datos desarrollada por el Departamento de Transporte de California (Caltrans) a través del software conocido como Performance Measurement System (PeMS). En esta base de datos se recopila información de forma continua, registrando los datos del tráfico vehicular a través de sensores instalados en diferentes vías de California, US." />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Capítulo 3 | Análisis Series de Tiempo de un conjunto de datos de tráfico" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Durante el curso de Análisis de Series de Tiempo se trabajará con una base de datos desarrollada por el Departamento de Transporte de California (Caltrans) a través del software conocido como Performance Measurement System (PeMS). En esta base de datos se recopila información de forma continua, registrando los datos del tráfico vehicular a través de sensores instalados en diferentes vías de California, US." />
  <meta name="github-repo" content="g6seriesdetiempo-ux/PEMSTrafficdata" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Capítulo 3 | Análisis Series de Tiempo de un conjunto de datos de tráfico" />
  
  <meta name="twitter:description" content="Durante el curso de Análisis de Series de Tiempo se trabajará con una base de datos desarrollada por el Departamento de Transporte de California (Caltrans) a través del software conocido como Performance Measurement System (PeMS). En esta base de datos se recopila información de forma continua, registrando los datos del tráfico vehicular a través de sensores instalados en diferentes vías de California, US." />
  

<meta name="author" content="Juliana Campo, Ludwig Angel" />


<meta name="date" content="2025-11-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="visualización-y-análisis-exploratorio-de-datos.html"/>
<link rel="next" href="capítulo-4.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis Series de Tiempo de un conjunto de datos de tráfico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Acerca</a></li>
<li class="chapter" data-level="2" data-path="03-Capitulo_3.html"><a href="#introducci%C3%B3n"><i class="fa fa-check"></i><b>2</b> Introducción</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>2.1</b> Conjunto de Datos Flujo Vehicular</a></li>
<li class="chapter" data-level="2.2" data-path="introducción.html"><a href="introducción.html#fuentes-y-permisos-de-uso"><i class="fa fa-check"></i><b>2.2</b> Fuentes y Permisos de Uso</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="03-Capitulo_3.html"><a href="#visualizaci%C3%B3n-y-an%C3%A1lisis-exploratorio-de-datos"><i class="fa fa-check"></i><b>3</b> Visualización y Análisis Exploratorio de Datos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="03-Capitulo_3.html"><a href="#preprocesamiento-de-datos-de-series-temporales-de-tr%C3%A1fico"><i class="fa fa-check"></i><b>3.1</b> Preprocesamiento de Datos de Series Temporales de Tráfico</a></li>
<li class="chapter" data-level="3.2" data-path="03-Capitulo_3.html"><a href="#integraci%C3%B3n-y-estructuraci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>3.2</b> Integración y Estructuración de Datos</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="03-Capitulo_3.html"><a href="#concatenaci%C3%B3n-de-archivos"><i class="fa fa-check"></i><b>3.2.1</b> Concatenación de Archivos</a></li>
<li class="chapter" data-level="3.2.2" data-path="03-Capitulo_3.html"><a href="#estandarizaci%C3%B3n-de-cabeceras"><i class="fa fa-check"></i><b>3.2.2</b> 2 Estandarización de Cabeceras</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="03-Capitulo_3.html"><a href="#diagn%C3%B3stico-y-limpieza-de-datos"><i class="fa fa-check"></i><b>3.3</b> Diagnóstico y Limpieza de Datos</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="03-Capitulo_3.html"><a href="#b-an%C3%A1lisis-del-mecanismo-de-datos-faltantes-mdm"><i class="fa fa-check"></i><b>3.3.1</b> B Análisis del Mecanismo de Datos Faltantes (MDM)</a></li>
<li class="chapter" data-level="3.3.2" data-path="03-Capitulo_3.html"><a href="#clasificaci%C3%B3n-del-mecanismo"><i class="fa fa-check"></i><b>3.3.2</b> Clasificación del Mecanismo</a></li>
<li class="chapter" data-level="3.3.3" data-path="visualización-y-análisis-exploratorio-de-datos.html"><a href="visualización-y-análisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>3.3.3</b> Estrategias de Filtrado</a></li>
<li class="chapter" data-level="3.3.4" data-path="visualización-y-análisis-exploratorio-de-datos.html"><a href="visualización-y-análisis-exploratorio-de-datos.html#sesgo-residual-potencial"><i class="fa fa-check"></i><b>3.3.4</b> Sesgo Residual Potencial</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="03-Capitulo_3.html"><a href="#agregaci%C3%B3n-temporal-y-reducci%C3%B3n-dimensional"><i class="fa fa-check"></i><b>3.4</b> Agregación Temporal y Reducción Dimensional</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="03-Capitulo_3.html"><a href="#transformaci%C3%B3n-de-granularidad-temporal"><i class="fa fa-check"></i><b>3.4.1</b> Transformación de Granularidad Temporal</a></li>
<li class="chapter" data-level="3.4.2" data-path="03-Capitulo_3.html"><a href="#estad%C3%ADsticas-de-agregaci%C3%B3n"><i class="fa fa-check"></i><b>3.4.2</b> Estadísticas de Agregación</a></li>
<li class="chapter" data-level="3.4.3" data-path="03-Capitulo_3.html"><a href="#evaluaci%C3%B3n-estad%C3%ADstica-media-vs.-mediana"><i class="fa fa-check"></i><b>3.4.3</b> Evaluación Estadística: Media vs. Mediana</a></li>
<li class="chapter" data-level="3.4.4" data-path="03-Capitulo_3.html"><a href="#resultados-de-asimetr%C3%ADa-gamma_1-datos-5-min"><i class="fa fa-check"></i><b>3.4.4</b> Resultados de Asimetría (<span class="math inline">\(\gamma_1\)</span>) (Datos 5-min)</a></li>
<li class="chapter" data-level="3.4.5" data-path="03-Capitulo_3.html"><a href="#diferencias-emp%C3%ADricas-agregados-horarios"><i class="fa fa-check"></i><b>3.4.5</b> Diferencias Empíricas (Agregados Horarios)</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="visualización-y-análisis-exploratorio-de-datos.html"><a href="visualización-y-análisis-exploratorio-de-datos.html#limitaciones-y-supuestos"><i class="fa fa-check"></i><b>3.5</b> Limitaciones y Supuestos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="03-Capitulo_3.html"><a href="#supuestos-impl%C3%ADcitos"><i class="fa fa-check"></i><b>3.5.1</b> Supuestos Implícitos</a></li>
<li class="chapter" data-level="3.5.2" data-path="03-Capitulo_3.html"><a href="#p%C3%A9rdidas-de-informaci%C3%B3n-documentadas"><i class="fa fa-check"></i><b>3.5.2</b> Pérdidas de Información Documentadas</a></li>
<li class="chapter" data-level="3.5.3" data-path="visualización-y-análisis-exploratorio-de-datos.html"><a href="visualización-y-análisis-exploratorio-de-datos.html#sesgos-no-cuantificados"><i class="fa fa-check"></i><b>3.5.3</b> Sesgos No Cuantificados</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualización-y-análisis-exploratorio-de-datos.html"><a href="visualización-y-análisis-exploratorio-de-datos.html#comportamiento-del-flujo-vehicular-en-el-tiempo"><i class="fa fa-check"></i><b>3.6</b> Comportamiento del flujo vehicular en el tiempo</a></li>
<li class="chapter" data-level="3.7" data-path="03-Capitulo_3.html"><a href="#distribuci%C3%B3n-de-la-velocidad-promedio-por-hora"><i class="fa fa-check"></i><b>3.7</b> Distribución de la velocidad promedio por hora</a></li>
<li class="chapter" data-level="3.8" data-path="03-Capitulo_3.html"><a href="#diagrama-de-dispersi%C3%B3n-del-flujo-vehicular-vs-velocidad-promedio"><i class="fa fa-check"></i><b>3.8</b> Diagrama de dispersión del flujo vehicular vs velocidad promedio</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="03-Capitulo_3.html"><a href="#cap%C3%ADtulo-3"><i class="fa fa-check"></i><b>4</b> Capítulo 3</a>
<ul>
<li class="chapter" data-level="4.1" data-path="03-Capitulo_3.html"><a href="#descomposici%C3%B3n-de-la-serie-temporal"><i class="fa fa-check"></i><b>4.1</b> Descomposición de la Serie Temporal</a></li>
<li class="chapter" data-level="4.2" data-path="03-Capitulo_3.html"><a href="#estacionariedad-y-diferenciaci%C3%B3n"><i class="fa fa-check"></i><b>4.2</b> Estacionariedad y Diferenciación</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="capítulo-3.html"><a href="capítulo-3.html"><i class="fa fa-check"></i><b>4.2.1</b> Test KPSS (Kwiatkowski-Phillips-Schmidt-Shin)</a></li>
<li class="chapter" data-level="4.2.2" data-path="03-Capitulo_3.html"><a href="#diferenciaci%C3%B3n-estacional"><i class="fa fa-check"></i><b>4.2.2</b> Diferenciación Estacional</a></li>
<li class="chapter" data-level="4.2.3" data-path="03-Capitulo_3.html"><a href="#confirmaci%C3%B3n-de-estacionariedad"><i class="fa fa-check"></i><b>4.2.3</b> Confirmación de Estacionariedad</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="03-Capitulo_3.html"><a href="#cap%C3%ADtulo-4"><i class="fa fa-check"></i><b>5</b> Capítulo 4</a>
<ul>
<li class="chapter" data-level="5.1" data-path="03-Capitulo_3.html"><a href="#fundamentaci%C3%B3n-metodol%C3%B3gica"><i class="fa fa-check"></i><b>5.1</b> Fundamentación Metodológica</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="capítulo-4.html"><a href="capítulo-4.html"><i class="fa fa-check"></i><b>5.1.1</b> Modelos Aditivos vs. Multiplicativos</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="03-Capitulo_3.html"><a href="#estimaci%C3%B3n-del-modelo"><i class="fa fa-check"></i><b>5.2</b> Estimación del Modelo</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="03-Capitulo_3.html"><a href="#confirmaci%C3%B3n-cuantitativa-de-la-estacionalidad"><i class="fa fa-check"></i><b>5.2.1</b> Confirmación Cuantitativa de la Estacionalidad</a></li>
<li class="chapter" data-level="5.2.2" data-path="capítulo-4.html"><a href="capítulo-4.html#nivel1-operadores-estacionales"><i class="fa fa-check"></i><b>5.2.2</b> Nivel 1: Operadores Estacionales</a></li>
<li class="chapter" data-level="5.2.3" data-path="capítulo-4.html"><a href="capítulo-4.html#nivel2-operadores-no-estacionales"><i class="fa fa-check"></i><b>5.2.3</b> Nivel 2: Operadores No Estacionales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="capitulo-5.html"><a href="capitulo-5.html"><i class="fa fa-check"></i><b>6</b> Capitulo 5</a></li>
<li class="divider"></li>
<li><a href="https://github.com/g6seriesdetiempo-ux/PEMSTrafficdata" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis Series de Tiempo de un conjunto de datos de tráfico</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="capítulo-3" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Capítulo 3<a href="#cap%C3%ADtulo-3" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="descomposición-de-la-serie-temporal" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Descomposición de la Serie Temporal<a href="#descomposici%C3%B3n-de-la-serie-temporal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dado que la variable FlujoTotal presenta una clara estructura temporal y estacionalidad diaria, es necesario realizar un análisis de series temporales para descomponer sus componentes, evaluar su estacionariedad y, si es necesario, aplicar transformaciones para prepararla para el modelado predictivo</p>
<p>La descomposición permite separar la serie en sus componentes principales: Tendencia, Estacionalidad e Irregularidad (ruido o error). Utilizamos el método STL (Seasonal-Trend decomposition using Loess), que es robusto a valores atípicos.La descomposición permite separar la serie en sus componentes principales: Tendencia, Estacionalidad e Irregularidad (ruido o error). Utilizamos el método STL (Seasonal-Trend decomposition using Loess), que es robusto a valores atípicos.</p>
<p>La descomposición es vital para entender la naturaleza de los picos y valles observados en el Capítulo anterior y para confirmar si la variabilidad del ruido es constante a lo largo del tiempo.</p>
<p><img src="my_gitbook_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Estacional: Muestra claramente el patrón diario consistente, con flujos altos en horas pico de la mañana y la tarde.</p>
<p>Tendencia: Muestra una ligera variación a largo plazo. Si bien no hay una tendencia lineal fuerte, la componente no es completamente plana.</p>
<p>Residual: Representa el componente irregular o ruido, que debería ser estacionario. Su magnitud parece ser relativamente constante, lo que simplifica el siguiente paso.</p>
<p>La descomposición STL revela una serie con fuerte componente estacional determinística y una tendencia suave pero significativa. El principal desafío estadístico es la heterocedasticidad residual, especialmente en el primer segmento de la serie. Esto sugiere que un modelo efectivo debería:</p>
</div>
<div id="estacionariedad-y-diferenciación" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Estacionariedad y Diferenciación<a href="#estacionariedad-y-diferenciaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una serie de tiempo es estacionaria si sus propiedades estadísticas (media, varianza, autocovarianza) no cambian con el tiempo. La estacionariedad es un requisito fundamental para modelos como ARIMA. La fuerte estacionalidad y la ligera tendencia observadas sugieren que la serie NO es estacionaria.</p>
<p>Se aplica la prueba de Dickey-Fuller Aumentada (ADF) a la serie temporal de interés (por ejemplo, velocidad promedio o flujo total) para evaluar la presencia de una raíz unitaria, que es un indicador de <strong>no estacionariedad</strong>.</p>
<ul>
<li><strong>Hipótesis Nula (<span class="math inline">\(H_0\)</span>):</strong> La serie temporal NO es estacionaria (contiene una raíz unitaria).</li>
<li><strong>Hipótesis Alternativa (<span class="math inline">\(H_a\)</span>):</strong> La serie temporal ES estacionaria.</li>
</ul>
<pre><code>## [1] &quot;Resultado de la prueba de Dickey-Fuller Aumentada (ADF) para el Flujo Total:&quot;</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  flujo_ts
## Dickey-Fuller = -29.143, Lag order = 15, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Métrica</th>
<th align="left">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>Estadístico ADF</strong></td>
<td align="left">-29.14</td>
</tr>
<tr class="even">
<td align="left"><strong>Valor <span class="math inline">\(p\)</span></strong></td>
<td align="left">0.01</td>
</tr>
<tr class="odd">
<td align="left"><strong>Nivel de Significación (<span class="math inline">\(\alpha\)</span>)</strong></td>
<td align="left"><span class="math inline">\(0.05\)</span></td>
</tr>
</tbody>
</table>
<p>El <strong>valor <span class="math inline">\(p\)</span> (<span class="math inline">\(p\)</span>-value)</strong> de la prueba ADF es 0.01. Dado que este valor es <strong>menor</strong> a <span class="math inline">\(0.05\)</span>, <strong>rechazamos</strong> la hipótesis nula (<span class="math inline">\(H_0\)</span>).</p>
<div id="test-kpss-kwiatkowski-phillips-schmidt-shin" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Test KPSS (Kwiatkowski-Phillips-Schmidt-Shin)<a href="capítulo-3.html#test-kpss-kwiatkowski-phillips-schmidt-shin" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La prueba KPSS es complementaria al ADF. Su hipótesis nula (<span class="math inline">\(H_0\)</span>) es que la serie ES estacionaria (alrededor de un nivel o una tendencia). Un p-value muy bajo indica que la serie es no estacionaria (rechaza <span class="math inline">\(H_0\)</span>).</p>
<pre><code>## [1] &quot;KPSS Test (Null: Estacionaria en Nivel):&quot;</code></pre>
<pre><code>## 
##  KPSS Test for Level Stationarity
## 
## data:  flujo_ts
## KPSS Level = 0.45417, Truncation lag parameter = 9, p-value = 0.05381</code></pre>
<pre><code>## [1] &quot;KPSS Test (Null: Estacionaria en Tendencia):&quot;</code></pre>
<pre><code>## 
##  KPSS Test for Trend Stationarity
## 
## data:  flujo_ts
## KPSS Trend = 0.0069695, Truncation lag parameter = 9, p-value = 0.1</code></pre>
<p>Basándose en el rechazo de la <span class="math inline">\(H_0\)</span> del test KPSS (confirmando no-estacionariedad) y los picos persistentes en los lags estacionales (24, 48, 72) de la ACF, se confirma que la serie requiere Diferenciación Estacional (<span class="math inline">\(D=1\)</span>, <span class="math inline">\(s=24\)</span>) para remover la fuerte estacionalidad estocástica antes de la identificación del modelo SARIMA.</p>
</div>
<div id="diferenciación-estacional" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Diferenciación Estacional<a href="#diferenciaci%C3%B3n-estacional" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para remover la estacionalidad diaria se aplica la diferenciación estacional.</p>
<p><img src="my_gitbook_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## [1] &quot;Resultado de la prueba ADF para la serie estacionalmente diferenciada:&quot;</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  flujo_diff_24
## Dickey-Fuller = -15.225, Lag order = 15, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
</div>
<div id="confirmación-de-estacionariedad" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Confirmación de Estacionariedad<a href="#confirmaci%C3%B3n-de-estacionariedad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La batería de pruebas estadísticas aplicadas proporciona evidencia concluyente sobre el comportamiento estocástico de la serie. La prueba de Dickey-Fuller Aumentada (ADF) arrojó un estadístico de -29.143 con un valor p de 0.01, rechazando contundentemente la hipótesis nula de presencia de raíz unitaria. Este resultado, complementado por las pruebas KPSS que mostraron valores marginales (p-value = 0.05381 para nivel y 0.1 para tendencia), confirma que la serie original presenta características mixtas de estacionariedad.</p>
<p><strong>La diferenciación estacional con lag 24</strong> se estableció como la transformación necesaria y suficiente para lograr estacionariedad plena. Tras aplicar esta diferenciación, la serie transformada exhibió un estadístico ADF de -15.225 (p-value = 0.01), confirmando que la serie diferenciada cumple con los requisitos de estacionariedad para la aplicación de modelos ARIMA estacionales (SARIMA).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualización-y-análisis-exploratorio-de-datos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="capítulo-4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/g6seriesdetiempo-ux/PEMSTrafficdata /edit/BRANCH/03-Capitulo_3.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["my_gitbook.pdf", "my_gitbook.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
